sonar.projectKey=Dorian88_embedded-payments
sonar.organization=Innosistemas-org
sonar.host.url=https://sonarcloud.io

# Rutas de codigo y pruebas
sonar.sources=src/main/java
sonar.tests=src/test/java

# Ruta donde JaCoCo dejara el reporte para que SonarCloud lo lea
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Lenguaje a analizar
sonar.java.binaries=target/classes
